/*
 * Reading routines for the binaries generated by Aky benchmark applications
 * and provides some structs to encapsulate the data and metadata
 */
#pragma once
#include <stdint.h>
#include <stddef.h>

struct Overhead {
  // TODO currently this is hardcoded in akypuera
  char hostname[256];
  uint32_t n;
  /* Return an estimator for the overhead in O(1) (e.g. mean) */
  double (*estimator)(void const *);
  void *data;
};

/* Read the overhead data from filename and summarize it by method */
struct Overhead *
overhead_read(char const *filename, int method, float trimming_factor);

void
overhead_del(struct Overhead *o);

struct Copytime {
  int minbytes, maxbytes, iters;
  double (*estimator)(struct Copytime const *, size_t bytes);
  double *data;
};

struct Copytime *
copytime_read(char const *filename);

void
copytime_del(struct Copytime *ct);
